/* Every string the studio shows or announces, in one flat object so a host can translate
 * it (`strings` prop) or ship a locale file. Placeholders are `{name}` and are filled by
 * `fmt`. Schema labels (param, option and item names) come from the engine catalogue. */

export const STRINGS = {
  studioLabel: 'Avatar studio',
  untitled: 'Untitled avatar',

  // Toolbar
  undo: 'Undo',
  redo: 'Redo',
  undoNamed: 'Undo: {label}',
  redoNamed: 'Redo: {label}',
  randomize: 'Randomize',
  randomizeHint: 'Roll a new avatar. Locked sections stay as they are.',
  theme: 'Theme',
  share: 'Share',
  export: 'Export',
  fromPhoto: 'From photo',
  fromPhotoHint: 'Make an avatar that looks like a photo. The photo stays on this device.',
  fromPhotoHintServer: 'Make an avatar that looks like a photo. ArkPlay looks at the photo and never keeps it.',
  save: 'Save',
  saving: 'Saving…',
  saved: 'Saved',
  cancel: 'Cancel',
  close: 'Close',
  draftSaved: 'Draft saved on this device',
  saveFailed: 'Couldn’t save: {message}',
  unknownError: 'Something went wrong.',

  // Name and kind
  name: 'Name',
  namePlaceholder: 'Name your avatar',
  kind: 'Avatar type',
  kind_humanoid: 'Humanoid',
  kind_creature: 'Creature',

  // Tabs
  tabs: 'Editor',
  tab_species: 'Species',
  tab_body: 'Body',
  tab_face: 'Face',
  tab_skin: 'Skin',
  tab_hair: 'Hair',
  tab_outfit: 'Outfit',
  tab_accessories: 'Accessories',
  tab_limbs: 'Limbs',
  tab_coat: 'Coat',
  tab_expression: 'Expression',
  tab_scene: 'Scene',
  tab_style: 'Style',
  tab_remix: 'Remix',
  tab_about: 'About',
  jumpTo: 'Jump to section',

  // Section cards and controls
  lockSection: 'Lock {section} when randomizing',
  unlockSection: 'Unlock {section}',
  randomizeSection: 'Randomize {section}',
  moreOptions: 'More options',
  fewerOptions: 'Fewer options',
  resetParam: 'Reset {param}',
  auto: 'Auto',
  autoColor: 'Automatic',
  customColor: 'Custom colour',
  colorValue: '{param}: {value}',
  on: 'On',
  off: 'Off',
  charCount: '{count}/{max}',
  selected: 'selected',

  // Preview
  preview: 'Avatar preview',
  view: 'View',
  view_front: 'Front',
  view_side: 'Side',
  view_back: 'Back',
  crop: 'Framing',
  crop_full: 'Full',
  crop_fit: 'Fit',
  crop_bust: 'Bust',
  crop_head: 'Head',
  crop_portrait: 'Portrait',
  zoomIn: 'Zoom in',
  zoomOut: 'Zoom out',
  zoomReset: 'Reset zoom',
  zoomLevel: '{percent}%',
  tryExpression: 'Try expression',
  tryPose: 'Try pose',
  ownExpression: 'Avatar’s own',
  ownPose: 'Avatar’s own',
  animation: 'Animation',
  animNone: 'Still',
  play: 'Play',
  pause: 'Pause',
  scrub: 'Animation time',
  timeReadout: '{time} / {duration}s',
  reducedMotionNote: 'Animations start paused because your device prefers reduced motion.',

  // Premium items on the stage (premium core: ArkPlay's servers draw them)
  premiumLocal: 'Premium items show as outlines here. ArkPlay draws them in your saved avatar.',
  premiumLoading: 'Drawing premium items…',
  premiumAnimating: 'Premium items show as outlines while animating.',
  premiumOffline: 'Couldn’t reach ArkPlay to draw premium items, so they show as outlines for now.',
  premiumBusy: 'ArkPlay is busy. Premium items show as outlines for a moment.',
  premiumUnavailable: 'Premium items show as outlines: this server doesn’t draw previews yet.',
  premiumTooLarge: 'With this custom art the avatar is too big to preview, so premium items show as outlines.',

  // Species
  speciesPicker: 'Species',
  speciesHelp: 'Start from a preset, then tweak anything.',
  speciesAll: 'All',
  speciesApply: 'Use {species}',

  // Wardrobe
  wearing: 'Wearing',
  wearingNone: 'Nothing here yet. Pick something below.',
  slotLabel: '{slot} ({count}/{capacity})',
  slotFullHint: 'Adding replaces {item}',
  none: 'None',
  equip: 'Wear {item}',
  unequip: 'Take off {item}',
  editItem: 'Edit {item}',
  removeItem: 'Remove {item}',
  moveUp: 'Draw {item} earlier',
  moveDown: 'Draw {item} later',
  itemAdded: 'Added {item}',
  itemReplaced: 'Added {item}, replacing {replaced}',
  itemRemoved: 'Removed {item}',
  lockOutfit: 'Lock outfit when randomizing',
  unlockOutfit: 'Unlock outfit',
  lockAccessories: 'Lock accessories when randomizing',
  unlockAccessories: 'Unlock accessories',
  outfitSection: 'Outfit',
  accessoriesSection: 'Accessories',

  // Custom art
  customTitle: 'Your own art',
  customHelp: 'Add a sticker, logo or drawing and pin it anywhere on your avatar.',
  customDrop: 'Drop an image here, or',
  customBrowse: 'choose a file',
  customTypes: 'PNG, SVG, JPEG or WebP',
  customUploading: 'Adding image…',
  customLocalWarning: 'This image is stored in the avatar on this device only. It isn’t saved to your account or included in share codes.',
  customTooBig: 'That image is too large. Try one under {size}.',
  customBadType: 'Use a PNG, SVG, JPEG or WebP image.',
  customFailed: 'Couldn’t add the image: {message}',
  customFull: 'You can add up to {max} images.',
  customImage: 'Custom image',

  // Saved outfits
  outfits: 'Saved looks',
  outfitsHelp: 'Save what your avatar is wearing and put it on any avatar later.',
  outfitName: 'Look name',
  outfitSave: 'Save look',
  outfitSaved: 'Look saved',
  outfitWear: 'Wear {name}',
  outfitDelete: 'Delete {name}',
  outfitDeleteConfirm: 'Delete {name}?',
  outfitEmpty: 'No saved looks yet.',
  outfitDefaultName: 'Look {n}',
  outfitLoadFailed: 'Couldn’t load saved looks.',
  outfitApplied: 'Wearing {name}',

  // Remix
  remixRandom: 'Surprise me',
  remixRandomHelp: 'Pick a theme and roll. Locked sections stay as they are.',
  lockedList: 'Locked: {list}',
  unlockAll: 'Unlock all',
  noLocks: 'Nothing is locked. Use the lock on any section to keep it while you roll.',
  variations: 'Variations',
  variationsHelp: 'Siblings of your avatar. Pick one to use it.',
  strength: 'How different',
  strength_subtle: 'Subtle',
  strength_medium: 'Medium',
  strength_wild: 'Wild',
  shuffle: 'Shuffle',
  useVariation: 'Use variation {n}',
  breed: 'Mix two avatars',
  breedHelp: 'Children take traits from you and a partner.',
  partner: 'Partner',
  rollPartner: 'New partner',
  partnerFromCode: 'Partner from a code',
  partnerCodeLabel: 'Partner’s code, link or JSON',
  partnerSet: 'Use as partner',
  useChild: 'Use child {n}',
  children: 'Children',
  you: 'You',
  morph: 'Morph',
  morphHelp: 'Slide from where you started towards the partner.',
  morphAmount: 'Morph amount',
  morphRestart: 'Start from current avatar',
  morphKindMismatch: 'Morphing needs two avatars of the same type.',
  details: 'Small details',
  detailsHelp: 'Re-roll freckle placement, hair strands and fur tufts without changing anything else.',
  shuffleDetails: 'Shuffle details',

  // About
  about: 'About this avatar',
  altText: 'Description (alt text)',
  altTextHelp: 'Screen readers read this wherever your avatar appears.',
  copy: 'Copy',
  copied: 'Copied',
  copyFailed: 'Couldn’t copy. Select the text and copy it yourself.',
  history: 'History',
  historyHelp: 'Jump back to any step. Undo and redo move one step at a time.',
  historyCurrent: 'Current step',
  shortcuts: 'Keyboard shortcuts',
  shortcutUndo: 'Undo',
  shortcutRedo: 'Redo',
  shortcutArrows: 'Move between options in a group',
  engine: 'Engine',

  // Free and PRO (tiers and features come from the engine: itemTier, FEATURES, PROMO)
  tierPro: 'PRO',
  tierLimited: 'LIMITED',
  tierNft: 'NFT',
  tierFreeUntil: 'Free until {date}',
  tierUntil: 'Until {date}',
  tierProFull: 'PRO · Free until {date}',
  tierLimitedFull: 'LIMITED · until {date}',
  tierProHint: '{item} is a PRO item, free for everyone until {date}.',
  tierProEnded: '{item} is a PRO item.',
  tierLimitedHint: '{item} is a limited edition, available until {date}.',
  tierLimitedEnded: '{item} is a limited edition.',
  tierNftHint: '{item} is only for holders of its NFT.',
  tierLegend: 'PRO and limited items are free to wear until {date}.',
  whatsFree: 'What’s free',
  whatsFreeHelp: 'Avatars have free and PRO features. Every PRO feature is free for everyone until {date}.',
  whatsFreeAfter: 'Avatars have free and PRO features.',
  freeForNow: 'Free for now',
  proFeatures: 'PRO features',
  freeForGood: 'Free for good',
  limitedItems: 'Limited editions',
  limitedItemsHelp: 'Founder items, only until {date}.',
  rarity: 'Rarity',
  rarityValue: '{tier} · score {score}',
  rarityHelp: 'Only PRO, limited and NFT items make an avatar rarer. Free choices never do.',
  rarity_common: 'Common',
  rarity_uncommon: 'Uncommon',
  rarity_rare: 'Rare',
  rarity_epic: 'Epic',
  rarity_legendary: 'Legendary',

  // Share
  shareTitle: 'Share and import',
  shareCode: 'Share code',
  shareCodeHelp: 'Anyone with this code can load a copy of your avatar.',
  copyCode: 'Copy code',
  copyLink: 'Copy link',
  linkCopied: 'Link copied',
  codeCopied: 'Code copied',
  shareCustomNote: 'Images stored only on this device aren’t included in codes or links.',
  importTitle: 'Import',
  importLabel: 'Paste a code, link or JSON',
  importLoad: 'Load avatar',
  importFile: 'Open a file',
  importEmpty: 'Paste a code or choose a file first.',
  importNotAvatar: 'That isn’t an avatar code, link or JSON file.',
  importBadJson: 'That JSON couldn’t be read: {message}',
  importWarnings: 'Loaded, with some changes:',
  importLoaded: 'Avatar loaded',
  jsonTitle: 'Avatar file',
  jsonHelp: 'A JSON file with everything, including images stored on this device.',
  downloadJson: 'Download JSON',

  // Export
  exportTitle: 'Export',
  format: 'Format',
  size: 'Size',
  sizeValue: '{size} px',
  sizeValuePro: '{size} px · {tier}',
  transparent: 'Transparent background',
  motion: 'Animated effects',
  quality: 'Quality',
  clip: 'Animation',
  clips: 'Animations',
  fps: 'Frame rate',
  fpsValue: '{fps} fps',
  length: 'Length',
  lengthValue: '{seconds} s',
  cell: 'Frame size',
  scale: 'Scale',
  scaleValue: '{scale}×',
  pixelGrid: 'Pixel grid',
  pixelGridValue: '{n}×{n}',
  exportButton: 'Export {format}',
  exporting: 'Exporting… {percent}%',
  exportDone: 'Downloaded {file}',
  exportFailed: 'Export failed: {message}',
  stageBusy: 'ArkPlay is busy drawing avatars. Your avatar will show in a moment.',
  stageOffline: 'ArkPlay can’t be reached, so your avatar can’t be drawn right now. Your changes are kept.',
  exportLocked: 'This download is a PRO feature. Unlock it on ArkPlay to download it.',
  exportBusy: 'ArkPlay is busy making downloads. Try again in a moment.',
  exportBusyRetry: 'ArkPlay is busy making downloads. Try again in {seconds} seconds.',
  exportOffline: 'ArkPlay can’t be reached right now, so this can’t be downloaded. Check your connection and try again.',
  exportTooLarge: 'This avatar is too large to download (custom art). Try a smaller image.',
  exportServerFailed: 'ArkPlay couldn’t make this download. Try again, or pick another format.',
  premiumExportNote: 'Premium items render on ArkPlay: this export gets them from ArkPlay’s servers.',
  premiumExportService: 'Premium items render on ArkPlay, and ArkPlay can’t be reached from here. Take them off to export, or try again later.',
  premiumExportFormat: 'Premium items render on ArkPlay, which can’t make this format for them right now. Try SVG, PNG, WebP, JPEG, pixel art or animated SVG.',
  exportCancelled: 'Export cancelled',
  cancelExport: 'Cancel',
  copyAlt: 'Copy alt text',
  altCopied: 'Alt text copied',
  selectAtLeastOne: 'Choose at least one animation.',
  exportPreview: 'Export preview',
  fmt_svg: 'SVG',
  fmtDesc_svg: 'Sharp at any size. Best for the web.',
  fmt_png: 'PNG',
  fmtDesc_png: 'A picture with optional transparency.',
  fmt_webp: 'WebP',
  fmtDesc_webp: 'Smaller than PNG, with transparency.',
  fmt_jpeg: 'JPEG',
  fmtDesc_jpeg: 'Small photo-style file, no transparency.',
  fmt_pixel: 'Pixel art',
  fmtDesc_pixel: 'Rendered on a tiny grid and scaled up crisp.',
  fmt_gif: 'GIF',
  fmtDesc_gif: 'Animated loop for chats and forums.',
  fmt_webm: 'WebM video',
  fmtDesc_webm: 'Smooth animated video clip.',
  'fmt_animated-svg': 'Animated SVG',
  'fmtDesc_animated-svg': 'One small file that animates in any browser.',
  fmt_spritesheet: 'Sprite sheet',
  fmtDesc_spritesheet: 'PNG grid + JSON for game engines (zip).',
  fmt_rig: 'Rig bundle',
  fmtDesc_rig: 'Cut-out parts atlas + bones and clips (zip).',
  fmt_stickers: 'Sticker pack',
  fmtDesc_stickers: 'Expressive stickers as PNGs (zip).',

  // Announcements and history labels
  randomized: 'New random avatar',
  randomizedSection: 'Randomized {section}',
  undid: 'Undid {label}',
  redid: 'Redid {label}',
  nothingToUndo: 'Nothing to undo',
  nothingToRedo: 'Nothing to redo',
  restoredDraft: 'Restored your draft',
  loadFailed: 'That avatar couldn’t be loaded: {message}',
  kindSwitched: 'Switched to {kind}',
  h_start: 'Start',
  h_randomize: 'Randomize',
  h_randomizeSection: 'Randomize {section}',
  h_species: 'Species: {species}',
  h_addItem: 'Add {item}',
  h_removeItem: 'Remove {item}',
  h_moveItem: 'Reorder {item}',
  h_itemParam: '{item}: {param}',
  h_outfit: 'Wear {name}',
  h_variation: 'Variation',
  h_child: 'Mixed avatar',
  h_morph: 'Morph',
  h_name: 'Name',
  h_kind: 'Switch to {kind}',
  h_load: 'Load avatar',
  h_seed: 'Shuffle details',
  h_jump: 'Jump to {label}',
  newLook: 'New look!',

  // From photo
  h_fromPhoto: 'Avatar from photo',
  photoTitle: 'Make an avatar from a photo',
  photoIntro: "We'll suggest a few avatars that look like the person in your photo. Pick one, then change anything you like.",
  photoPrivacy: "Your photo is processed right here on this device. It's never uploaded, saved or shared, and it's gone when you close this window.",
  photoPermission: 'Use a photo of yourself, or one you have permission to use.',
  photoNoGuessing: "We only look at things like hair, colours and face shape. Nothing guesses your gender, age or background, and you choose everything in the end.",
  photoPrivacyServer: "Your photo is sent to ArkPlay over an encrypted connection and looked at in memory for a few seconds. It's never saved, logged or shared, and only the avatar you pick is kept.",
  photoServerBusy: 'ArkPlay is busy looking at photos. Try again in a moment.',
  photoServerOffline: 'ArkPlay can’t be reached right now. Check your connection and try again.',
  photoDownloadNote: 'The first time, the photo tools (about 30 MB) download to your browser.',
  photoChoose: 'Choose a photo',
  photoUseCamera: 'Use camera',
  photoCameraPreview: 'Camera preview',
  photoTake: 'Take photo',
  forgeNewQuest: 'New quest',
  forgeQuest: 'Quest',
  forgeQuestName: 'Forge your avatar',
  forgeBoot: 'Lighting the forge',
  forgeModels: 'Gather the photo tools',
  forgeFaces: 'Find the face',
  forgeSegmentation: 'Spot hair and outfit',
  forgeMeasure: 'Mix the colours',
  forgeAttributes: 'Read the style',
  forgeSynth: 'Forge the avatar',
  forgeLevel: 'Level {level}',
  forgeLevelUp: 'Level up!',
  forgeLoot: 'Traits unlocked',
  lootHair: 'Hair',
  lootEyes: 'Eyes',
  lootSkin: 'Skin tone',
  lootMatched: 'Matched',
  lootFacialHair: 'Facial hair',
  lootOutfit: 'Outfit',
  lootGear: 'Gear',
  heroesTag: 'Choose your hero',
  heroBest: 'Best match',
  scanMB: '{loaded} / {total} MB',
  photoPick: 'Pick the closest one. You can change everything after.',
  photoUse: 'Play as this avatar',
  photoRetry: 'Try again',
  photoAnother: 'Another photo',
  photoNotes: 'How we read your photo ({count})',
  photoNoFace: "We couldn't find a face. Try a photo where your face is clearly visible and facing the camera.",
  photoTooSmall: 'The face is too small in this photo. Try a closer one.',
  photoTooDark: 'This photo is too dark. Try one with more light.',
  photoToolsFailed: "The photo tools couldn't load. Check your connection and try again.",
  photoCameraFailed: "We couldn't open the camera. You can choose a photo instead.",
  photoFailed: "Something went wrong reading that photo. Try another one.",
}

export type StudioStrings = { [K in keyof typeof STRINGS]: string }

/** Fills `{name}` placeholders. Unknown placeholders are left as they are. */
export function fmt(template: string, vars: Record<string, string | number> = {}): string {
  return template.replace(/\{(\w+)\}/g, (m, k: string) => (k in vars ? String(vars[k]) : m))
}

export function mergeStrings(over?: Partial<StudioStrings>): StudioStrings {
  return over ? { ...STRINGS, ...over } : STRINGS
}
