/* Creature species presets. A preset is not a separate kind of thing: it is a starting
 * set of values for the same creature params, so every preset can be edited, mixed and
 * mutated into something new. "Dragon" is a quadruped with bat wings, horns and scales. */

import type { Params } from './params.ts'

export interface SpeciesPreset {
  id: string
  label: string
  tags: readonly string[]
  sections: Record<string, Params>
}

const P = (
  id: string,
  label: string,
  plan: string,
  tags: string[],
  s: Record<string, Params>,
): SpeciesPreset => ({ id, label, tags, sections: { ...s, species: { plan, ...(s.species ?? {}) } } })

export const SPECIES: SpeciesPreset[] = [
  P('cat', 'Cat', 'quadruped', ['animal', 'cute', 'pet'], {
    form: { length: 0.45, girth: 0.4, neck: 0.3, belly: 0.35, fluff: 0.3 },
    face: { headShape: 'round', snout: 0.18, eyeStyle: 'cute', pupil: 'slit', mouth: 'cat', iris: '#7cb342', cheeks: 0.3 },
    ears: { style: 'pointed', size: 0.55 },
    tail: { style: 'thin', length: 0.75, curve: 0.75, thickness: 0.4 },
    limbs: { feet: 'paws', length: 0.45 },
    extras: { whiskers: true },
    coat: { primary: '#e8a55a', secondary: '#f2efe9', pattern: 'stripes', patternColor: '#b8651f', texture: 'fur' },
  }),
  P('dog', 'Dog', 'quadruped', ['animal', 'cute', 'pet'], {
    form: { length: 0.55, girth: 0.5, neck: 0.4, fluff: 0.25 },
    face: { headShape: 'round', snout: 0.55, eyeStyle: 'cute', mouth: 'smile', iris: '#5b3a1e', tongue: true },
    ears: { style: 'floppy', size: 0.6 },
    tail: { style: 'thin', length: 0.55, curve: 0.85 },
    limbs: { feet: 'paws', length: 0.5 },
    coat: { primary: '#c89a64', secondary: '#f2efe9', pattern: 'patches', patternColor: '#6d4c41', texture: 'fur' },
  }),
  P('fox', 'Fox', 'quadruped', ['animal', 'forest'], {
    form: { length: 0.55, girth: 0.4, neck: 0.4, fluff: 0.45 },
    face: { headShape: 'wedge', snout: 0.62, eyeStyle: 'round', pupil: 'slit', mouth: 'smile', iris: '#d4a017', cheeks: 0.55 },
    ears: { style: 'pointed', size: 0.72 },
    tail: { style: 'bushy', length: 0.85, thickness: 0.7, curve: 0.55 },
    limbs: { feet: 'paws', length: 0.5 },
    coat: { primary: '#e8742a', secondary: '#f7f1e8', pattern: 'socks', patternColor: '#3a2a22', texture: 'fur' },
  }),
  P('wolf', 'Wolf', 'quadruped', ['animal', 'forest', 'fantasy'], {
    form: { length: 0.62, girth: 0.52, neck: 0.45, fluff: 0.55 },
    face: { headShape: 'wedge', snout: 0.7, eyeStyle: 'fierce', mouth: 'fangs', iris: '#40c4ff', cheeks: 0.6 },
    ears: { style: 'pointed', size: 0.6 },
    tail: { style: 'bushy', length: 0.75, thickness: 0.6, curve: 0.3 },
    limbs: { feet: 'claws', length: 0.6 },
    coat: { primary: '#8a8f99', secondary: '#e6e6ea', pattern: 'saddle', patternColor: '#4b4f58', texture: 'fur' },
  }),
  P('bear', 'Bear', 'quadruped', ['animal', 'forest', 'cute'], {
    species: { size: 0.65 },
    form: { length: 0.55, girth: 0.82, neck: 0.25, belly: 0.7, fluff: 0.5 },
    face: { headShape: 'round', snout: 0.4, eyeStyle: 'dot', mouth: 'smile', iris: '#2a1a10' },
    ears: { style: 'round', size: 0.4 },
    tail: { style: 'none' },
    limbs: { feet: 'pads', length: 0.4, thickness: 0.8 },
    coat: { primary: '#7a4b2a', secondary: '#c8a27a', pattern: 'none', texture: 'fur' },
  }),
  P('bunny', 'Bunny', 'quadruped', ['animal', 'cute', 'pet'], {
    species: { size: 0.35, stance: 0.3 },
    form: { length: 0.35, girth: 0.55, neck: 0.2, belly: 0.6, fluff: 0.6 },
    face: { headShape: 'round', snout: 0.12, eyeStyle: 'cute', mouth: 'cat', iris: '#3b2314', cheeks: 0.5 },
    ears: { style: 'long', size: 0.85 },
    tail: { style: 'fluffy', length: 0.12, thickness: 0.8 },
    limbs: { feet: 'pads', length: 0.3 },
    extras: { whiskers: true },
    coat: { primary: '#f2efe9', secondary: '#ffffff', pattern: 'none', texture: 'fur' },
  }),
  P('mouse', 'Mouse', 'quadruped', ['animal', 'cute'], {
    species: { size: 0.2, stance: 0.35 },
    form: { length: 0.4, girth: 0.45, neck: 0.2, belly: 0.5 },
    face: { headShape: 'wedge', snout: 0.5, eyeStyle: 'dot', mouth: 'cat', iris: '#1a1a1a' },
    ears: { style: 'round', size: 0.8 },
    tail: { style: 'thin', length: 0.9, thickness: 0.15, curve: 0.6 },
    limbs: { feet: 'pads', length: 0.3 },
    extras: { whiskers: true },
    coat: { primary: '#9e9e9e', secondary: '#e6e6ea', pattern: 'none', texture: 'fur' },
  }),
  P('lion', 'Lion', 'quadruped', ['animal', 'royal'], {
    species: { size: 0.7 },
    form: { length: 0.6, girth: 0.6, neck: 0.4, fluff: 0.3 },
    face: { headShape: 'round', snout: 0.45, eyeStyle: 'round', mouth: 'smile', iris: '#b07d2b' },
    ears: { style: 'round', size: 0.35 },
    tail: { style: 'tuft', length: 0.75, curve: 0.35 },
    limbs: { feet: 'paws', length: 0.55, thickness: 0.65 },
    extras: { mane: 'lion' },
    coat: { primary: '#e0b060', secondary: '#f2e2c0', accent: '#8b4a1c', pattern: 'none', texture: 'fur' },
  }),
  P('tiger', 'Tiger', 'quadruped', ['animal', 'jungle'], {
    species: { size: 0.7 },
    form: { length: 0.65, girth: 0.55, neck: 0.4 },
    face: { headShape: 'round', snout: 0.4, eyeStyle: 'fierce', mouth: 'smile', iris: '#d4a017', cheeks: 0.55 },
    ears: { style: 'round', size: 0.4 },
    tail: { style: 'thin', length: 0.8, thickness: 0.45, curve: 0.45 },
    limbs: { feet: 'paws', length: 0.55, thickness: 0.65 },
    extras: { whiskers: true },
    coat: { primary: '#f08a24', secondary: '#fbf5ec', pattern: 'tiger', patternColor: '#241a14', texture: 'fur' },
  }),
  P('horse', 'Horse', 'quadruped', ['animal', 'farm'], {
    species: { size: 0.8, stance: 0.85 },
    form: { length: 0.65, girth: 0.5, neck: 0.8, belly: 0.35 },
    face: { headShape: 'long', snout: 0.9, eyeStyle: 'round', mouth: 'smile', iris: '#3b2314' },
    ears: { style: 'pointed', size: 0.35 },
    tail: { style: 'bushy', length: 0.75, thickness: 0.5, curve: 0.2 },
    limbs: { feet: 'hooves', length: 0.8, thickness: 0.45 },
    extras: { mane: 'horse' },
    coat: { primary: '#8d5a36', secondary: '#f2efe9', accent: '#2f2320', pattern: 'socks', patternColor: '#f2efe9', texture: 'smooth' },
  }),
  P('deer', 'Deer', 'quadruped', ['animal', 'forest'], {
    species: { size: 0.6, stance: 0.75 },
    form: { length: 0.5, girth: 0.42, neck: 0.65 },
    face: { headShape: 'long', snout: 0.55, eyeStyle: 'cute', mouth: 'smile', iris: '#2a1a10' },
    ears: { style: 'pointed', size: 0.55 },
    horns: { style: 'antlers', size: 0.6, color: '#c8a27a' },
    tail: { style: 'fluffy', length: 0.15 },
    limbs: { feet: 'hooves', length: 0.75, thickness: 0.35 },
    coat: { primary: '#b8763e', secondary: '#f2e6d8', pattern: 'spots', patternColor: '#f7f0e6', patternScale: 0.35, texture: 'fur' },
  }),
  P('unicorn', 'Unicorn', 'quadruped', ['fantasy', 'cute', 'magic'], {
    species: { size: 0.75, stance: 0.8 },
    form: { length: 0.6, girth: 0.48, neck: 0.75 },
    face: { headShape: 'long', snout: 0.75, eyeStyle: 'cute', mouth: 'smile', iris: '#8067a8' },
    ears: { style: 'pointed', size: 0.35 },
    horns: { style: 'unicorn', size: 0.7, color: '#f2d14a' },
    tail: { style: 'bushy', length: 0.8, curve: 0.3 },
    limbs: { feet: 'hooves', length: 0.75, thickness: 0.4 },
    extras: { mane: 'horse' },
    coat: { primary: '#fbf6ff', secondary: '#ffffff', accent: '#ff8ac8', pattern: 'none', texture: 'smooth' },
  }),
  P('dragon', 'Dragon', 'quadruped', ['fantasy', 'dragon'], {
    species: { size: 0.75 },
    form: { length: 0.65, girth: 0.55, neck: 0.6, belly: 0.5 },
    face: { headShape: 'wedge', snout: 0.7, eyeStyle: 'fierce', pupil: 'slit', mouth: 'fangs', iris: '#f2d14a' },
    ears: { style: 'fin', size: 0.5 },
    horns: { style: 'curved', size: 0.6, color: '#f2e6c8' },
    tail: { style: 'spade', length: 0.9, thickness: 0.6, curve: 0.45 },
    wings: { style: 'bat', size: 0.7 },
    limbs: { feet: 'claws', length: 0.5, thickness: 0.6 },
    extras: { spikes: 0.6 },
    coat: { primary: '#2e9e5b', secondary: '#f0e0a0', belly: '#f0e0a0', accent: '#c0392b', pattern: 'scales', patternColor: '#237a45', texture: 'scales' },
  }),
  P('griffin', 'Griffin', 'quadruped', ['fantasy', 'royal'], {
    species: { size: 0.75 },
    form: { length: 0.6, girth: 0.52, neck: 0.5, fluff: 0.5 },
    face: { headShape: 'wedge', snout: 0.4, eyeStyle: 'fierce', mouth: 'hooked', iris: '#d4a017' },
    ears: { style: 'tufted', size: 0.45 },
    tail: { style: 'tuft', length: 0.7 },
    wings: { style: 'feather', size: 0.75 },
    limbs: { feet: 'talons', length: 0.55, thickness: 0.6 },
    coat: { primary: '#c89a4a', secondary: '#f7f1e8', accent: '#f2d14a', pattern: 'gradient', patternColor: '#f7f1e8', texture: 'feathers' },
  }),
  P('frog', 'Frog', 'quadruped', ['animal', 'water', 'cute'], {
    species: { size: 0.3, stance: 0.2 },
    form: { length: 0.35, girth: 0.7, neck: 0.1, belly: 0.7 },
    face: { headShape: 'flat', snout: 0.1, eyeStyle: 'cute', mouth: 'smile', iris: '#d4a017', eyeSize: 0.7 },
    ears: { style: 'none' },
    tail: { style: 'none' },
    limbs: { feet: 'webbed', length: 0.4, thickness: 0.6 },
    coat: { primary: '#6ab04c', secondary: '#e6f4c0', belly: '#e6f4c0', pattern: 'spots', patternColor: '#3f7a2c', patternScale: 0.4, texture: 'smooth' },
  }),
  P('turtle', 'Turtle', 'quadruped', ['animal', 'water', 'cute'], {
    species: { size: 0.4, stance: 0.25 },
    form: { length: 0.45, girth: 0.55, neck: 0.4 },
    face: { headShape: 'round', snout: 0.25, eyeStyle: 'dot', mouth: 'smile' },
    ears: { style: 'none' },
    tail: { style: 'thin', length: 0.15, thickness: 0.5 },
    limbs: { feet: 'pads', length: 0.3, thickness: 0.8 },
    extras: { shell: 'turtle' },
    coat: { primary: '#8bc34a', secondary: '#e6f4c0', accent: '#6d4c41', pattern: 'none', texture: 'smooth' },
  }),
  P('axolotl', 'Axolotl', 'quadruped', ['animal', 'water', 'cute'], {
    species: { size: 0.35, stance: 0.2 },
    form: { length: 0.55, girth: 0.45, neck: 0.2, belly: 0.4 },
    face: { headShape: 'flat', snout: 0.1, eyeStyle: 'dot', mouth: 'smile', eyeSize: 0.35 },
    ears: { style: 'frill', size: 0.7, inner: '#e84393' },
    tail: { style: 'fin', length: 0.7, thickness: 0.5, curve: 0.5 },
    limbs: { feet: 'pads', length: 0.3, thickness: 0.45 },
    coat: { primary: '#ffb6c9', secondary: '#ffe3ea', accent: '#e84393', pattern: 'none', texture: 'slime' },
  }),
  P('dino', 'Dinosaur', 'avian', ['animal', 'fantasy'], {
    species: { size: 0.75, stance: 0.6 },
    form: { length: 0.6, girth: 0.6, neck: 0.4, belly: 0.5 },
    face: { headShape: 'boxy', snout: 0.75, eyeStyle: 'round', mouth: 'jaws', iris: '#d4a017', headSize: 0.65 },
    ears: { style: 'none' },
    tail: { style: 'thin', length: 0.9, thickness: 0.8, curve: 0.45 },
    wings: { style: 'none' },
    limbs: { feet: 'claws', length: 0.6, thickness: 0.8 },
    extras: { spikes: 0.3 },
    coat: { primary: '#5aa36b', secondary: '#e8f0c0', belly: '#e8f0c0', pattern: 'bands', patternColor: '#3f7a4c', texture: 'scales' },
  }),
  P('owl', 'Owl', 'avian', ['animal', 'forest', 'wizard'], {
    species: { size: 0.4, stance: 0.3 },
    form: { length: 0.35, girth: 0.75, neck: 0.1, belly: 0.7, fluff: 0.5 },
    face: { headShape: 'round', snout: 0.1, eyeStyle: 'round', mouth: 'hooked', iris: '#f2b31a', eyeSize: 0.8, headSize: 0.7 },
    ears: { style: 'tufted', size: 0.5 },
    tail: { style: 'feather', length: 0.25 },
    wings: { style: 'feather', size: 0.45 },
    limbs: { feet: 'talons', length: 0.2 },
    coat: { primary: '#8b6a4a', secondary: '#e8d8c0', belly: '#e8d8c0', pattern: 'spots', patternColor: '#5c4330', patternScale: 0.25, texture: 'feathers' },
  }),
  P('parrot', 'Parrot', 'avian', ['animal', 'jungle', 'pirate'], {
    species: { size: 0.35, stance: 0.45 },
    form: { length: 0.4, girth: 0.5, neck: 0.25, belly: 0.45 },
    face: { headShape: 'round', snout: 0.35, eyeStyle: 'round', mouth: 'hooked', iris: '#f2f2f2' },
    ears: { style: 'none' },
    tail: { style: 'feather', length: 0.8, curve: 0.3 },
    wings: { style: 'feather', size: 0.5, color: '#1e88e5' },
    limbs: { feet: 'talons', length: 0.3 },
    coat: { primary: '#e53935', secondary: '#fdd835', belly: '#fdd835', accent: '#1e88e5', pattern: 'gradient', patternColor: '#fdd835', texture: 'feathers' },
  }),
  P('penguin', 'Penguin', 'avian', ['animal', 'winter', 'cute'], {
    species: { size: 0.4, stance: 0.4 },
    form: { length: 0.3, girth: 0.72, neck: 0.1, belly: 0.75 },
    face: { headShape: 'round', snout: 0.25, eyeStyle: 'dot', mouth: 'beak', headSize: 0.6 },
    ears: { style: 'none' },
    tail: { style: 'none' },
    wings: { style: 'feather', size: 0.3, color: '#26252c' },
    limbs: { feet: 'webbed', length: 0.12 },
    coat: { primary: '#26252c', secondary: '#f7f7f7', belly: '#f7f7f7', accent: '#fb8c00', pattern: 'none', texture: 'smooth' },
  }),
  P('duck', 'Duck', 'avian', ['animal', 'water', 'cute'], {
    species: { size: 0.3, stance: 0.35 },
    form: { length: 0.45, girth: 0.6, neck: 0.35, belly: 0.6 },
    face: { headShape: 'round', snout: 0.3, eyeStyle: 'dot', mouth: 'duck' },
    ears: { style: 'none' },
    tail: { style: 'feather', length: 0.2, curve: 0.8 },
    wings: { style: 'feather', size: 0.35 },
    limbs: { feet: 'webbed', length: 0.2 },
    coat: { primary: '#fdd835', secondary: '#fff59d', accent: '#fb8c00', pattern: 'none', texture: 'feathers' },
  }),
  P('fish', 'Fish', 'aquatic', ['animal', 'water'], {
    species: { size: 0.35 },
    form: { length: 0.5, girth: 0.6 },
    face: { headShape: 'round', snout: 0.2, eyeStyle: 'round', mouth: 'smile', eyeSize: 0.6 },
    ears: { style: 'none' },
    tail: { style: 'fin', length: 0.5, thickness: 0.7 },
    extras: { fins: true },
    coat: { primary: '#ff8a3d', secondary: '#fbf5ec', pattern: 'bands', patternColor: '#fbf5ec', texture: 'scales' },
  }),
  P('shark', 'Shark', 'aquatic', ['animal', 'water'], {
    species: { size: 0.8 },
    form: { length: 0.75, girth: 0.45 },
    face: { headShape: 'wedge', snout: 0.6, eyeStyle: 'dot', mouth: 'jaws' },
    ears: { style: 'none' },
    tail: { style: 'fin', length: 0.6, thickness: 0.6 },
    extras: { fins: true },
    coat: { primary: '#7f95a8', secondary: '#f2f4f6', belly: '#f2f4f6', pattern: 'none', texture: 'smooth' },
  }),
  P('whale', 'Whale', 'aquatic', ['animal', 'water', 'cute'], {
    species: { size: 0.9 },
    form: { length: 0.7, girth: 0.85, belly: 0.6 },
    face: { headShape: 'boxy', snout: 0.3, eyeStyle: 'dot', mouth: 'smile', eyeSize: 0.3 },
    ears: { style: 'none' },
    tail: { style: 'fin', length: 0.45, thickness: 0.8 },
    coat: { primary: '#4f7aa8', secondary: '#dde9f5', belly: '#dde9f5', pattern: 'none', texture: 'smooth' },
  }),
  P('snake', 'Snake', 'serpent', ['animal', 'jungle'], {
    form: { length: 0.8, girth: 0.35 },
    face: { headShape: 'wedge', snout: 0.35, eyeStyle: 'round', pupil: 'slit', mouth: 'smile', tongue: true, iris: '#d4a017' },
    ears: { style: 'none' },
    tail: { style: 'thin' },
    coat: { primary: '#7cb342', secondary: '#e6f4c0', pattern: 'bands', patternColor: '#33691e', texture: 'scales' },
  }),
  P('eastern-dragon', 'Sky dragon', 'serpent', ['fantasy', 'dragon', 'cultural'], {
    species: { size: 0.8 },
    form: { length: 0.9, girth: 0.45 },
    face: { headShape: 'long', snout: 0.6, eyeStyle: 'fierce', mouth: 'fangs', iris: '#f2d14a' },
    ears: { style: 'fin', size: 0.5 },
    horns: { style: 'antlers', size: 0.6, color: '#f2d14a' },
    limbs: { legs: '4', feet: 'claws', length: 0.3 },
    tail: { style: 'flame', length: 0.6 },
    extras: { whiskers: true, mane: 'crest', spikes: 0.2 },
    coat: { primary: '#d32f2f', secondary: '#f2d14a', belly: '#f7e08a', accent: '#f2d14a', pattern: 'scales', patternColor: '#a82424', texture: 'scales' },
  }),
  P('snail', 'Snail', 'serpent', ['animal', 'cute', 'nature'], {
    species: { size: 0.25 },
    form: { length: 0.3, girth: 0.5 },
    face: { headShape: 'round', snout: 0.1, eyeStyle: 'dot', mouth: 'smile' },
    ears: { style: 'none' },
    horns: { style: 'antenna', size: 0.5, color: '#c8b4a0' },
    extras: { shell: 'snail' },
    coat: { primary: '#c8b4a0', secondary: '#efe6dc', accent: '#c0703a', pattern: 'none', texture: 'slime' },
  }),
  P('bee', 'Bee', 'insectoid', ['animal', 'cute', 'nature'], {
    species: { size: 0.2 },
    form: { length: 0.4, girth: 0.75, belly: 0.6, fluff: 0.5 },
    face: { headShape: 'round', snout: 0.05, eyeStyle: 'cute', mouth: 'smile', iris: '#2a1a10' },
    ears: { style: 'none' },
    horns: { style: 'antenna', size: 0.5, color: '#26252c' },
    wings: { style: 'insect', size: 0.55 },
    tail: { style: 'stinger', length: 0.2 },
    limbs: { legs: '6', length: 0.25, feet: 'pads' },
    coat: { primary: '#fdd835', secondary: '#fff3a0', pattern: 'bands', patternColor: '#26252c', texture: 'fur' },
  }),
  P('butterfly', 'Butterfly', 'insectoid', ['animal', 'nature', 'cute'], {
    species: { size: 0.2 },
    form: { length: 0.5, girth: 0.3 },
    face: { headShape: 'round', snout: 0.05, eyeStyle: 'cute', mouth: 'smile' },
    ears: { style: 'none' },
    horns: { style: 'antenna', size: 0.7, color: '#26252c' },
    wings: { style: 'fairy', size: 0.85, color: '#fb8c00' },
    tail: { style: 'none' },
    limbs: { legs: '6', length: 0.25 },
    coat: { primary: '#37474f', secondary: '#546e7a', accent: '#fdd835', pattern: 'none', texture: 'smooth' },
  }),
  P('ladybug', 'Ladybug', 'insectoid', ['animal', 'cute', 'nature'], {
    species: { size: 0.18 },
    form: { length: 0.4, girth: 0.7 },
    face: { headShape: 'round', snout: 0.05, eyeStyle: 'dot', mouth: 'smile' },
    ears: { style: 'none' },
    horns: { style: 'antenna', size: 0.4, color: '#26252c' },
    tail: { style: 'none' },
    limbs: { legs: '6', length: 0.2 },
    extras: { shell: 'turtle' },
    coat: { primary: '#26252c', secondary: '#37474f', accent: '#e53935', pattern: 'spots', patternColor: '#141319', texture: 'smooth' },
  }),
  P('spider', 'Spider', 'insectoid', ['animal', 'spooky'], {
    species: { size: 0.25 },
    form: { length: 0.45, girth: 0.7, fluff: 0.6 },
    face: { headShape: 'round', snout: 0.05, eyeCount: '8', eyeStyle: 'dot', mouth: 'fangs' },
    ears: { style: 'none' },
    tail: { style: 'none' },
    limbs: { legs: '8', length: 0.7, thickness: 0.3 },
    coat: { primary: '#37303a', secondary: '#5c4f60', pattern: 'none', texture: 'fur' },
  }),
  P('beetle', 'Beetle', 'insectoid', ['animal', 'nature'], {
    species: { size: 0.22 },
    form: { length: 0.5, girth: 0.6 },
    face: { headShape: 'round', snout: 0.1, eyeStyle: 'dot', mouth: 'mandibles' },
    ears: { style: 'none' },
    horns: { style: 'straight', size: 0.6, color: '#2b3a67' },
    tail: { style: 'none' },
    limbs: { legs: '6', length: 0.35 },
    extras: { shell: 'turtle' },
    coat: { primary: '#2b3a67', secondary: '#3949ab', accent: '#1e88e5', pattern: 'none', texture: 'metal' },
  }),
  P('slime', 'Slime', 'blob', ['fantasy', 'cute'], {
    species: { size: 0.35 },
    form: { blobShape: 'drop', girth: 0.6 },
    face: { eyeStyle: 'cute', mouth: 'smile', iris: '#1a1a1a' },
    ears: { style: 'none' },
    tail: { style: 'none' },
    coat: { primary: '#6ee08a', secondary: '#c8f7d4', pattern: 'none', texture: 'slime' },
  }),
  P('ghost', 'Ghost', 'blob', ['spooky', 'cute', 'fantasy'], {
    species: { size: 0.4 },
    form: { blobShape: 'ghost', girth: 0.5 },
    face: { eyeStyle: 'dot', mouth: 'smile', iris: '#1a1a1a' },
    ears: { style: 'none' },
    tail: { style: 'none' },
    limbs: { arms: 'stubby' },
    coat: { primary: '#f4f6fb', secondary: '#dfe5f2', pattern: 'none', texture: 'smooth' },
  }),
  P('mochi', 'Mochi', 'blob', ['cute', 'food'], {
    species: { size: 0.3 },
    form: { blobShape: 'mochi', girth: 0.8 },
    face: { eyeStyle: 'dot', mouth: 'cat' },
    ears: { style: 'round', size: 0.3 },
    tail: { style: 'none' },
    coat: { primary: '#ffd1dc', secondary: '#fff0f4', pattern: 'none', texture: 'smooth' },
  }),
  P('wisp', 'Fire wisp', 'blob', ['fantasy', 'magic'], {
    species: { size: 0.3 },
    form: { blobShape: 'flame', girth: 0.5 },
    face: { eyeStyle: 'cute', mouth: 'smile', glow: true, iris: '#fff59d' },
    ears: { style: 'none' },
    tail: { style: 'none' },
    coat: { primary: '#ff7043', secondary: '#ffd54f', pattern: 'gradient', patternColor: '#ffd54f', texture: 'smooth' },
  }),
  P('octopus', 'Octopus', 'cephalopod', ['animal', 'water', 'cute'], {
    species: { size: 0.4 },
    form: { length: 0.5, girth: 0.6 },
    face: { eyeStyle: 'cute', mouth: 'smile', iris: '#1a1a1a' },
    ears: { style: 'none' },
    limbs: { length: 0.55 },
    tail: { style: 'none' },
    coat: { primary: '#ef6c7a', secondary: '#ffd0d6', pattern: 'spots', patternColor: '#ffb0bb', patternScale: 0.3, texture: 'slime' },
  }),
  P('jelly', 'Jellyfish', 'cephalopod', ['animal', 'water', 'magic'], {
    species: { size: 0.35 },
    form: { length: 0.3, girth: 0.7 },
    face: { eyeStyle: 'dot', mouth: 'cat', glow: false },
    ears: { style: 'none' },
    limbs: { length: 0.8, thickness: 0.2 },
    tail: { style: 'none' },
    coat: { primary: '#b39ddb', secondary: '#e8e0ff', pattern: 'gradient', patternColor: '#f8bbd0', texture: 'slime' },
  }),
  P('robot', 'Robot', 'robot', ['scifi', 'robot'], {
    species: { size: 0.55 },
    form: { build: 'box', girth: 0.55 },
    face: { eyeStyle: 'visor', mouth: 'grill', iris: '#00e5ff', glow: true },
    ears: { style: 'none' },
    horns: { style: 'antenna', size: 0.5, color: '#b0bec5' },
    limbs: { legs: '2', arms: 'long', feet: 'pads', length: 0.5 },
    tail: { style: 'none' },
    coat: { primary: '#b0bec5', secondary: '#eceff1', accent: '#ff7043', pattern: 'none', texture: 'metal' },
  }),
  P('bot-tv', 'Retro bot', 'robot', ['scifi', 'retro', 'cute'], {
    species: { size: 0.45 },
    form: { build: 'tv', girth: 0.6 },
    face: { eyeStyle: 'dot', mouth: 'smile', iris: '#1a1a1a' },
    ears: { style: 'none' },
    horns: { style: 'antenna', size: 0.7, color: '#8a8580' },
    limbs: { legs: '0', arms: 'stubby', feet: 'wheels' },
    tail: { style: 'none' },
    coat: { primary: '#f2b134', secondary: '#dff5f0', accent: '#e53935', pattern: 'none', texture: 'metal' },
  }),
  P('drone', 'Drone', 'robot', ['scifi'], {
    species: { size: 0.3 },
    form: { build: 'round', girth: 0.5 },
    face: { eyeCount: '1', eyeStyle: 'round', mouth: 'none', iris: '#e53935', glow: true },
    ears: { style: 'none' },
    limbs: { legs: '0', arms: 'none' },
    wings: { style: 'mech', size: 0.5 },
    tail: { style: 'none' },
    coat: { primary: '#eceff1', secondary: '#90a4ae', accent: '#e53935', pattern: 'circuit', patternColor: '#90a4ae', texture: 'metal' },
  }),
]

const byId = new Map(SPECIES.map((s) => [s.id, s]))
export const speciesPreset = (id: string): SpeciesPreset | undefined => byId.get(id)
